### ISSUE TITLE
sbt-web tester does not work

### ISSUE THREAD

**Issue by antonkulaga** [sbt/sbt-web#119] opened 2015-07-25 13:17 UTC
```
/home/antonkulaga/denigma/sbt-web/build.sbt:12: error: eof expected but ';' found.
resolvers += "scalaz-bintray" at "https://dl.bintray.com/scalaz/releases"
``

**Comment by huntc** [comment] 2016-04-16 06:53
Is this still an issue for you?

**Comment by huntc** [comment] 2016-04-18 04:59
Closing - cannot reproduce

**Closed by huntc** 2016-04-18 04:59 UTC
